services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Porta principal de acesso aos serviços
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb # Ativa só o DynamoDB (pode colocar mais serviços depois)
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
